# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-radium
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      qa_network:
        ipv4_address: 172.18.0.2
  chrome:
    image: selenium/node-chrome:3.141.59-radium
    container_name: chrome-node
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    #swarm mode
  #deploy:
        #replicas: 1
    #entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
      qa_network:
        ipv4_address: 172.18.0.3
  firefox:
    image: selenium/node-firefox:3.141.59-radium
    container_name: firefox-node
    ports:
      - "5902:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      #swarm mode
      #deploy:
        #replicas: 1
    #entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
    networks:
      qa_network:
        ipv4_address: 172.18.0.4
 
networks:
    qa_network:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16